#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service single
SERVICE_NAME="meilisearch"

check_container_initialized
check_service_initialized init

if [ "${MEILISEARCH_SETUP_TYPE,,}" = "auto" ]; then
    config_args="--config-file-path ${CONFIG_PATH%/}/${CONFIG_FILE}"
fi

liftoff

print_start "Starting Meilisearch $(meilisearch -V | head -n1 | awk '{print $2}')"
set -x
exec s6-setuidgid "${MEILISEARCH_USER}" meilisearch ${config_args} ${MEILISEARCH_ADDITIONAL_ARGS}
set +x